controller_manager:
  ros__parameters:
    use_sim_time: True
    update_rate: 1000  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
      
    easyrobot_controller:
      type: joint_trajectory_controller/JointTrajectoryController
      
#Controller for the easybot must have the same name as in the moveit_controllers.yaml file
easyrobot_controller:
  ros__parameters:
    type: "joint_trajectory_controller/JointTrajectoryController"
    joints:
      - joint1
      - joint2
    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity
    gains:
      joint1:
        p: 1000.0
        i: 20.0
        d: 100.0
        i_clamp: 30.0
        antiwindup: true
      joint2:
        p: 150.0
        i: 5.0
        d: 30.0
        i_clamp: 10.0
        antiwindup: true
    allow_nonzero_velocity_at_trajectory_end: true
    constraints:
      goal_time: 1.0
      stopped_velocity_tolerance: 0.1
      joint1:
        goal: 0.1
        #trajectory: 0.1 ##With high speeds the controller is not able to follow the preplaned path. WIP!
      joint2:
        goal: 0.1
        #trajectory: 0.1 ##With high speeds the controller is not able to follow the preplaned path. WIP!
