# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - moveit_arm_controller

  moveit_arm_controller:
    type: FollowJointTrajectory
    joints:
      - joint1
      - joint2
    action_ns: follow_joint_trajectory
    default: true