  controller_names:
    - easyrobot_controller
    
  #Controller for the easybot must have the same name as in the easybot_controller.yaml file
  easyrobot_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - joint1
      - joint2

